closes issue 9: New issue 9 by j.nick.terry: handler doesn't verify www-authenticate exists http://code.google.com/p/python-ntlm/issues/detail?id=9
I'm at trying to authenticate with a server that uses NTLM.  However it
doesn't set the www-authenticate header.  The handler assumes this value
exists and tries set it to lower.  Since the server doesn't return that
header, python throws an exception about None not having a lower method.

Traceback (most recent call last):
 File "nyquist_scrape.py", line 24, in <module>
   response = urllib2.urlopen(url)
 File "/usr/lib/python2.5/urllib2.py", line 124, in urlopen
   return _opener.open(url, data)
 File "/usr/lib/python2.5/urllib2.py", line 387, in open
   response = meth(req, response)
 File "/usr/lib/python2.5/urllib2.py", line 498, in http_response
   'http', request, response, code, msg, hdrs)
 File "/usr/lib/python2.5/urllib2.py", line 419, in error
   result = self._call_chain(*args)
 File "/usr/lib/python2.5/urllib2.py", line 360, in _call_chain
   result = func(*args)
 File "/home/nickte/test/moderation/ntlm/HTTPNtlmAuthHandler.py", line 92,
in http_error_401
   return self.http_error_authentication_required('www-authenticate', req,
fp, headers)
 File "/home/nickte/test/moderation/ntlm/HTTPNtlmAuthHandler.py", line 30,
in http_error_authentication_required
   if 'ntlm' in auth_header_value.lower():
AttributeError: 'NoneType' object has no attribute 'lower'

git-svn-id: http://python-ntlm.googlecode.com/svn/trunk/python26@76 fb9420a8-c688-11dd-8ca8-e3ff79f713b6